### ISSUE TITLE
run highlight_heuristic.py error

### ISSUE THREAD

**Issue by QiuJianL** [ucfnlp/summarization-sing-pair-mix#6]
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "F:\summarization-sing-pair-mix-master\highlight_heuristic.py", line 37, in process_one_example
    summary_sent_tokens, article_sent_tokens, vocab=None, sentence_limit=FLAGS.sentence_limit, min_matched_tokens=FLAGS.min_matched_tokens)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 473, in __getattr__
    raise AttributeError(name)
AttributeError: sentence_limit
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:/summarization-sing-pair-mix-master/highlight_heuristic.py", line 117, in <module>
    app.run(main)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "F:/summarization-sing-pair-mix-master/highlight_heuristic.py", line 95, in main
    list(tqdm(pool.imap(process_one_example, ex_list), total=total))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tqdm\_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\pool.py", line 735, in next
    raise value
AttributeError: sentence_limit

Where is this wrong? Thanks for your advice

**Comment by loganlebanoff** [comment]
I did not run into this problem, but it should be fixed now with the [newest version](https://github.com/ucfnlp/summarization-sing-pair-mix/commit/e275b3a993f33186c27c50138f197b11bb99910b). Can you try again with this change and see if it works?

**Comment by QiuJianL** [comment]
Cool,This method can solve the problem I am facing.Thanks
